# Generated by Django 4.1 on 2022-09-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_userhassession_userhascourse"),
    ]

    operations = [
        migrations.AddField(
            model_name="userclient",
            name="has_courses",
            field=models.ManyToManyField(to="src.course"),
        ),
        migrations.AddField(
            model_name="userclient",
            name="has_sessions",
            field=models.ManyToManyField(to="src.session"),
        ),
    ]
